#### Introduction to Numpy

In [1]:
import numpy as np

In [3]:
# Creating a numpy array from a list
list1 = [1,2,3,4,5,6,7,8]

a = np.array(list1)
print(a)
print(type(a))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [4]:
# Creating 2D arrays using lists
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)
print(type(b))
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


In [5]:
# Creating 3D arrays using lists
c = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[11,21,31], [41,51,61], [71,81,91]], [[12,22,32], [42,52,62], [72,82,92]]])
print(c)
print(type(c))
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 21 31]
  [41 51 61]
  [71 81 91]]

 [[12 22 32]
  [42 52 62]
  [72 82 92]]]
<class 'numpy.ndarray'>
(3, 3, 3)


In [10]:
# Creating a list using arange method

d = np.arange(0, 30, 2)
print(d)
print(type(d))
print(d.shape)

# Converting this array into a matrix
e = d.reshape(5,3)
print(e)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
<class 'numpy.ndarray'>
(15,)
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]


In [14]:
# Creating a list using linspace method -- linspace includes both the start and end values
f = np.linspace(0,6,10)
print(f)
print(type(f))
print(f.shape)

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]
<class 'numpy.ndarray'>
(10,)


In [25]:
# If the number of values in linspace is not defined, the deault number of values is 50. 
# The elements in the array range from (upper_value * 0)/(n-1), (upper_value*1)/(n-1),....(upper_value * (n-1))/(n-1)
g = np.linspace(0, 50)
print(g)
print(type(g))
print(g.shape)
print(len(g))

[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]
<class 'numpy.ndarray'>
(50,)
50


In [24]:
h=np.linspace(0,2,4)
print(h)

[0.         0.66666667 1.33333333 2.        ]


In [28]:
# Get the dimensions of the array
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
1
1
1


In [29]:
# Get the type of data stored in the array
print(a.dtype)
print(d.dtype)
print(f.dtype)
print(h.dtype)

int64
int64
float64
float64


In [31]:
# Get the size of the array
print("Number of elements are: ", f.size)
print("Number of bytes occupied: ", f.nbytes)
print("Number of bytes occupied by each element: ", f.itemsize)

Number of elements are:  10
Number of bytes occupied:  80
Number of bytes occupied by each element:  8


In [34]:
# Using special methods to create arrays

h = np.zeros([3,2])
print(h)
print(type(h))
print(h.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>
float64


In [42]:
i = np.ones([4,4])
print(i)
print(type(i))
print(i.dtype)
print(i.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>
float64
(4, 4)


In [39]:
j = np.eye(3)
print(j)
print(type(j))
print(j.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>
(3, 3)


In [40]:
# Using full method to create an array -- Need to include the shape of the array/matrix and the element to fill in
k = np.full([3,3], 5)
print(k)
print(type(k))
print(k.shape)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
<class 'numpy.ndarray'>
(3, 3)


In [41]:
# Using full_like to create an array -- Need to include an existing matrix and the value to fill in
l = np.full_like(i, 2.1)
print(l)
print(type(l))
print(l.shape)

[[2.1 2.1 2.1 2.1]
 [2.1 2.1 2.1 2.1]
 [2.1 2.1 2.1 2.1]
 [2.1 2.1 2.1 2.1]]
<class 'numpy.ndarray'>
(4, 4)


In [43]:
# Generating an array from random data
m = np.random.rand(4,2) # Generates a unifrom random distribution between 0 and 1 with mean 0.5
print(m)
print(type(m))
print(m.shape)

[[0.26950335 0.69295387]
 [0.05860459 0.66118073]
 [0.18201874 0.15048587]
 [0.22200297 0.37164512]]
<class 'numpy.ndarray'>
(4, 2)


In [45]:
n = np.random.randint(0, 10, size=(2,4)) # Generates a random integer between 0 and 10  
print(n)
print(type(n))
print(n.shape)

[[1 5 5 5]
 [4 5 9 8]]
<class 'numpy.ndarray'>
(2, 4)


In [63]:
o = np.random.randn(2,3) # Generates a normal distribution with mean 0 and standard deviation 1
print(o)
print(type(o))
print(o.shape)

[[-1.12779439  0.07770769 -0.1270936 ]
 [-0.28744075 -1.01919001 -0.09367824]]
<class 'numpy.ndarray'>
(2, 3)
